# Site settings
title: Valley Insurance Agency
email: info@via-inc.com
description: >
  For over 35 years, Valley Insurance has provided a variety of insurance
  products and services, along with experienced, knowledgeable personnel
  dedicated to assisting you in protecting your assets and liabilities.
baseurl: ""
url: "http://via-inc.github.io"

# Build settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
markdown: kramdown
permalink: /:categories/:title